import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sorry but our website on maintenance</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn-icons.flaticon.com/png/512/5305/premium/5305390.png?token=exp=1639422002~hmac=dfc628845749712553eb322609b83284"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Offline for <a href="https://nextjs.org">maintenance!</a>
        </h1>

        <p className={styles.description}>
          This app is undergoing maintenance right now.
          <br />
          Please check back later.
        </p>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Check our twitter! &rarr;</h2>
            <p>
              Go to our twitter and check status or news. Also we in future add
              our blog!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://instagram.com/coderpy.4" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by CoderPY4
        </a>
      </footer>
    </div>
  );
}
